
-- 0005_chunks_meta.sql
ALTER TABLE chunks ADD COLUMN title TEXT NOT NULL DEFAULT '';
ALTER TABLE chunks ADD COLUMN section_path TEXT NOT NULL DEFAULT '';
ALTER TABLE chunks ADD COLUMN heading_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chunks ADD COLUMN summary TEXT NOT NULL DEFAULT '';
ALTER TABLE chunks ADD COLUMN content_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE chunks ADD COLUMN token_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chunks ADD COLUMN char_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chunks ADD COLUMN parent_chunk_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chunks ADD COLUMN prev_chunk_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chunks ADD COLUMN next_chunk_id INTEGER NOT NULL DEFAULT 0;
