// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatMessage {
    "id": number;
    "sessionId": number;
    "role": string;
    "content": string;
    "createdAt": number;
}

export interface ChatSession {
    "id": number;
    "title": string;
    "collectionId": number;
    "createdAt": number;
    "archived": boolean;
    "pinned": boolean;
}

export interface Collection {
    "id": number;
    "name": string;
    "docCount": number;
    "createdAt": number;
}

export interface Document {
    "id": number;
    "collectionId": number;
    "filename": string;
    "summary": string;
    "hash": string;
    "content": string;
    "createdAt": number;
    "chunkCount": number;
}

export interface SourceChunkRef {
    "id": number;
    "messageId": number;
    "sessionId": number;
    "chunkId": number;
    "filename": string;
    "collectionId": number;
    "collectionName": string;
    "similarity": number;
    "content": string;
    "refNumber": number;
}
