// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChatMessage {
    /**
     * Creates a new ChatMessage instance.
     * @param {Partial<ChatMessage>} [$$source = {}] - The source object to create the ChatMessage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionId"] = 0;
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cancelled"] = false;
        }
        if (!("parentMessageId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["parentMessageId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["agentMetadataJson"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessage(/** @type {Partial<ChatMessage>} */($$parsedSource));
    }
}

export class ChatSession {
    /**
     * Creates a new ChatSession instance.
     * @param {Partial<ChatSession>} [$$source = {}] - The source object to create the ChatSession.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("currentLeafMessageId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentLeafMessageId"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["archived"] = false;
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatSession}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSession(/** @type {Partial<ChatSession>} */($$parsedSource));
    }
}

export class ChatSessionMemory {
    /**
     * Creates a new ChatSessionMemory instance.
     * @param {Partial<ChatSessionMemory>} [$$source = {}] - The source object to create the ChatSessionMemory.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionId"] = 0;
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("memoryType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["memoryType"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("sourceMessageId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sourceMessageId"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSessionMemory instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatSessionMemory}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSessionMemory(/** @type {Partial<ChatSessionMemory>} */($$parsedSource));
    }
}

export class ChunkRecord {
    /**
     * Creates a new ChunkRecord instance.
     * @param {Partial<ChunkRecord>} [$$source = {}] - The source object to create the ChunkRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("documentId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["documentId"] = 0;
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("ord" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ord"] = 0;
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["level"] = 0;
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("parentOrd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["parentOrd"] = 0;
        }
        if (!("prevOrd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["prevOrd"] = 0;
        }
        if (!("nextOrd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nextOrd"] = 0;
        }
        if (!("chunkHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chunkHash"] = "";
        }
        if (!("embeddingHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embeddingHash"] = "";
        }
        if (!("headingPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["headingPath"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChunkRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChunkRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChunkRecord(/** @type {Partial<ChunkRecord>} */($$parsedSource));
    }
}

export class Collection {
    /**
     * Creates a new Collection instance.
     * @param {Partial<Collection>} [$$source = {}] - The source object to create the Collection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("docCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["docCount"] = 0;
        }
        if (!("embeddingModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embeddingModel"] = "";
        }
        if (!("embeddingDims" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["embeddingDims"] = 0;
        }
        if (!("vectorBackend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vectorBackend"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Collection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Collection(/** @type {Partial<Collection>} */($$parsedSource));
    }
}

export class Document {
    /**
     * Creates a new Document instance.
     * @param {Partial<Document>} [$$source = {}] - The source object to create the Document.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("sourceType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceType"] = "";
        }
        if (!("sourceSizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sourceSizeBytes"] = 0;
        }
        if (!("wordCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["wordCount"] = 0;
        }
        if (!("lineCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lineCount"] = 0;
        }
        if (!("characterCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["characterCount"] = 0;
        }
        if (!("paragraphCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["paragraphCount"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("chunkCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunkCount"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("expectedChunks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedChunks"] = 0;
        }
        if (!("batchId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["batchId"] = "";
        }
        if (!("errorMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["errorMessage"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Document}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Document(/** @type {Partial<Document>} */($$parsedSource));
    }
}

/**
 * DuplicateMatch describes a likely duplicate document found during staging.
 */
export class DuplicateMatch {
    /**
     * Creates a new DuplicateMatch instance.
     * @param {Partial<DuplicateMatch>} [$$source = {}] - The source object to create the DuplicateMatch.
     */
    constructor($$source = {}) {
        if (!("documentId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["documentId"] = 0;
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DuplicateMatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DuplicateMatch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DuplicateMatch(/** @type {Partial<DuplicateMatch>} */($$parsedSource));
    }
}

/**
 * EventLogEntry captures durable workspace activity for diagnostics.
 */
export class EventLogEntry {
    /**
     * Creates a new EventLogEntry instance.
     * @param {Partial<EventLogEntry>} [$$source = {}] - The source object to create the EventLogEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("eventKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventKey"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("chatId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chatId"] = 0;
        }
        if (!("docId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["docId"] = 0;
        }
        if (!("batchId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["batchId"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventLogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventLogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventLogEntry(/** @type {Partial<EventLogEntry>} */($$parsedSource));
    }
}

/**
 * ExtensionHook describes one future integration surface (GraphRAG, SQL Agent,
 * MCP, OCR, etc.). The table is intentionally small and generic so new hook
 * points can be added without schema churn.
 */
export class ExtensionHook {
    /**
     * Creates a new ExtensionHook instance.
     * @param {Partial<ExtensionHook>} [$$source = {}] - The source object to create the ExtensionHook.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("hookKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hookKey"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hookType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hookType"] = "";
        }
        if (!("surface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surface"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("configJson" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configJson"] = "";
        }
        if (!("lastRunAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastRunAt"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionHook instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtensionHook}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtensionHook(/** @type {Partial<ExtensionHook>} */($$parsedSource));
    }
}

export class IngestionJob {
    /**
     * Creates a new IngestionJob instance.
     * @param {Partial<IngestionJob>} [$$source = {}] - The source object to create the IngestionJob.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("batchId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["batchId"] = "";
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("progressPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progressPct"] = 0;
        }
        if (!("totalDocuments" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalDocuments"] = 0;
        }
        if (!("completedDocuments" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completedDocuments"] = 0;
        }
        if (!("failedDocuments" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedDocuments"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("retryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retryCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("pausedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pausedAt"] = 0;
        }
        if (!("resumedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resumedAt"] = 0;
        }
        if (!("cancelledAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cancelledAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IngestionJob instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IngestionJob}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IngestionJob(/** @type {Partial<IngestionJob>} */($$parsedSource));
    }
}

export class IngestionLog {
    /**
     * Creates a new IngestionLog instance.
     * @param {Partial<IngestionLog>} [$$source = {}] - The source object to create the IngestionLog.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("jobId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["jobId"] = 0;
        }
        if (!("documentId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["documentId"] = 0;
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("batchId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["batchId"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("memoryBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memoryBytes"] = 0;
        }
        if (!("throughput" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["throughput"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IngestionLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IngestionLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IngestionLog(/** @type {Partial<IngestionLog>} */($$parsedSource));
    }
}

export class SourceChunkRef {
    /**
     * Creates a new SourceChunkRef instance.
     * @param {Partial<SourceChunkRef>} [$$source = {}] - The source object to create the SourceChunkRef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["messageId"] = 0;
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionId"] = 0;
        }
        if (!("chunkId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunkId"] = 0;
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("collectionName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collectionName"] = "";
        }
        if (!("similarity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["similarity"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("refNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["refNumber"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceChunkRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceChunkRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceChunkRef(/** @type {Partial<SourceChunkRef>} */($$parsedSource));
    }
}
