// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatMessage {
    "id": number;
    "sessionId": number;
    "role": string;
    "content": string;
    "createdAt": number;
    "cancelled": boolean;
    "parentMessageId": number;
    "agentMetadataJson"?: string;
}

export interface ChatSession {
    "id": number;
    "title": string;
    "collectionId": number;
    "currentLeafMessageId": number;
    "createdAt": number;
    "archived": boolean;
    "pinned": boolean;
}

export interface ChatSessionMemory {
    "id": number;
    "sessionId": number;
    "collectionId": number;
    "memoryType": string;
    "summary": string;
    "sourceMessageId": number;
    "createdAt": number;
    "updatedAt": number;
}

export interface ChunkRecord {
    "id": number;
    "documentId": number;
    "collectionId": number;
    "content": string;
    "summary": string;
    "ord": number;
    "level": number;
    "role": string;
    "parentOrd": number;
    "prevOrd": number;
    "nextOrd": number;
    "chunkHash": string;
    "embeddingHash": string;
    "headingPath": string;
    "updatedAt": number;
}

export interface Collection {
    "id": number;
    "name": string;
    "docCount": number;
    "embeddingModel": string;
    "embeddingDims": number;
    "vectorBackend": string;
    "createdAt": number;
    "updatedAt": number;
}

export interface Document {
    "id": number;
    "collectionId": number;
    "filename": string;
    "summary": string;
    "hash": string;
    "content": string;
    "sourceType": string;
    "sourceSizeBytes": number;
    "wordCount": number;
    "lineCount": number;
    "characterCount": number;
    "paragraphCount": number;
    "title": string;
    "createdAt": number;
    "chunkCount": number;
    "status": string;
    "expectedChunks": number;
    "batchId": string;
    "errorMessage": string;
    "updatedAt": number;
}

/**
 * DuplicateMatch describes a likely duplicate document found during staging.
 */
export interface DuplicateMatch {
    "documentId": number;
    "collectionId": number;
    "filename": string;
    "kind": string;
    "score": number;
    "reason": string;
}

/**
 * EventLogEntry captures durable workspace activity for diagnostics.
 */
export interface EventLogEntry {
    "id": number;
    "eventKey": string;
    "title": string;
    "detail": string;
    "severity": string;
    "scope": string;
    "collectionId": number;
    "chatId": number;
    "docId": number;
    "batchId": string;
    "createdAt": number;
}

export interface IngestionJob {
    "id": number;
    "batchId": string;
    "collectionId": number;
    "status": string;
    "stage": string;
    "progressPct": number;
    "totalDocuments": number;
    "completedDocuments": number;
    "failedDocuments": number;
    "message": string;
    "retryCount": number;
    "createdAt": number;
    "updatedAt": number;
    "pausedAt": number;
    "resumedAt": number;
    "cancelledAt": number;
}

export interface IngestionLog {
    "id": number;
    "jobId": number;
    "documentId": number;
    "collectionId": number;
    "batchId": string;
    "level": string;
    "stage": string;
    "message": string;
    "durationMs": number;
    "memoryBytes": number;
    "throughput": number;
    "createdAt": number;
}

export interface MCPConfiguration {
    "enabled": boolean;
    "servers": MCPServer[] | null;
}

export interface MCPServer {
    "name": string;
    "configJson": string;
    "enabled": boolean;
    "verified": boolean;
    "toolCount": number;
    "toolsJson": string;
    "lastError": string;
    "lastVerifiedAt": number;
    "enabledTools": string[] | null;
}

export interface SourceChunkRef {
    "id": number;
    "messageId": number;
    "sessionId": number;
    "chunkId": number;
    "filename": string;
    "collectionId": number;
    "collectionName": string;
    "similarity": number;
    "content": string;
    "refNumber": number;
}
