// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {number} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveChat(sessionID) {
    return $Call.ByID(369086432, sessionID);
}

/**
 * â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
 * CancelGeneration cancels an in-progress streaming generation for a session.
 * @param {number} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CancelGeneration(sessionID) {
    return $Call.ByID(4129843748, sessionID);
}

/**
 * CancelIngest requests cancellation of the active ingest worker.
 * @returns {$CancellablePromise<void>}
 */
export function CancelIngest() {
    return $Call.ByID(2481471630);
}

/**
 * CheckFileHash checks if a file hash already exists in a collection.
 * @param {string} hash
 * @param {number} collectionID
 * @returns {$CancellablePromise<$models.FileUploadResult | null>}
 */
export function CheckFileHash(hash, collectionID) {
    return $Call.ByID(1617768898, hash, collectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CleanupIncompleteOnStartup removes staging rows and resets interrupted embedding jobs.
 * @returns {$CancellablePromise<void>}
 */
export function CleanupIncompleteOnStartup() {
    return $Call.ByID(1378031294);
}

/**
 * @param {string} title
 * @param {number} collectionID
 * @returns {$CancellablePromise<number>}
 */
export function CreateChat(title, collectionID) {
    return $Call.ByID(1198129586, title, collectionID);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<number>}
 */
export function CreateCollection(name) {
    return $Call.ByID(870896888, name);
}

/**
 * @param {number} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteChat(sessionID) {
    return $Call.ByID(3616999957, sessionID);
}

/**
 * @param {number} collectionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCollection(collectionID) {
    return $Call.ByID(492526307, collectionID);
}

/**
 * @param {number} docID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDocument(docID) {
    return $Call.ByID(2035697934, docID);
}

/**
 * DiscardAllIncomplete deletes all non-ready documents.
 * @returns {$CancellablePromise<number>}
 */
export function DiscardAllIncomplete() {
    return $Call.ByID(924053369);
}

/**
 * DiscardIngestJob deletes one incomplete document.
 * @param {number} docID
 * @returns {$CancellablePromise<void>}
 */
export function DiscardIngestJob(docID) {
    return $Call.ByID(2725518913, docID);
}

/**
 * @param {number} sessionID
 * @returns {$CancellablePromise<store$0.ChatMessage[]>}
 */
export function GetChatMessages(sessionID) {
    return $Call.ByID(227903766, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<store$0.ChatSession[]>}
 */
export function GetChats() {
    return $Call.ByID(3792084875).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<store$0.Collection[]>}
 */
export function GetCollections() {
    return $Call.ByID(3945395097).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetDocumentContent returns the full extracted text content of a document.
 * @param {number} docID
 * @returns {$CancellablePromise<string>}
 */
export function GetDocumentContent(docID) {
    return $Call.ByID(4234809594, docID);
}

/**
 * @param {number} collectionID
 * @returns {$CancellablePromise<store$0.Document[]>}
 */
export function GetDocumentsByCollection(collectionID) {
    return $Call.ByID(1237202507, collectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetIncompleteJobs returns non-ready documents for resume/discard UI.
 * @returns {$CancellablePromise<$models.IngestJob[]>}
 */
export function GetIncompleteJobs() {
    return $Call.ByID(153934368).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetMessageSources returns source chunks for a given message.
 * @param {number} msgID
 * @returns {$CancellablePromise<store$0.SourceChunkRef[]>}
 */
export function GetMessageSources(msgID) {
    return $Call.ByID(2286181287, msgID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetSessionSources returns source chunks all messages in a session.
 * @param {number} sessionID
 * @returns {$CancellablePromise<store$0.SourceChunkRef[]>}
 */
export function GetSessionSources(sessionID) {
    return $Call.ByID(2419631210, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * IngestFile stages pasted text then embeds via the durable two-phase pipeline.
 * @param {number} collectionID
 * @param {string} filename
 * @param {string} fileContent
 * @returns {$CancellablePromise<void>}
 */
export function IngestFile(collectionID, filename, fileContent) {
    return $Call.ByID(1283934766, collectionID, filename, fileContent);
}

/**
 * IsIngesting reports whether staging/embedding is currently running.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsIngesting() {
    return $Call.ByID(1844145288);
}

/**
 * NewBatchID returns a new random batch identifier.
 * @returns {$CancellablePromise<string>}
 */
export function NewBatchID() {
    return $Call.ByID(335305559);
}

/**
 * @param {number} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function PinChat(sessionID) {
    return $Call.ByID(3755018561, sessionID);
}

/**
 * ResumeIngest continues embedding for all resumable incomplete documents.
 * @returns {$CancellablePromise<$models.IngestBatchResult | null>}
 */
export function ResumeIngest() {
    return $Call.ByID(1682414391).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} query
 * @param {number} collectionID
 * @returns {$CancellablePromise<$models.SearchResult[]>}
 */
export function Search(query, collectionID) {
    return $Call.ByID(2413095468, query, collectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {number} sessionID
 * @param {number} collectionID
 * @param {string} prompt
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(sessionID, collectionID, prompt) {
    return $Call.ByID(279711485, sessionID, collectionID, prompt);
}

/**
 * StartIngestBatch stages every file first, then embeds all staged jobs in the batch.
 * @param {number} collectionID
 * @param {$models.IngestFilePayload[]} files
 * @returns {$CancellablePromise<$models.IngestBatchResult | null>}
 */
export function StartIngestBatch(collectionID, files) {
    return $Call.ByID(3830860924, collectionID, files).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {number} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function UnarchiveChat(sessionID) {
    return $Call.ByID(3611384037, sessionID);
}

/**
 * @param {number} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function UnpinChat(sessionID) {
    return $Call.ByID(206193300, sessionID);
}

/**
 * @param {number} sessionID
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function UpdateChatTitle(sessionID, title) {
    return $Call.ByID(239667623, sessionID, title);
}

/**
 * UploadFile stages one file then embeds it via the durable two-phase pipeline.
 * Prefer StartIngestBatch for multi-file uploads (extract-all-then-embed).
 * @param {string} filename
 * @param {string} base64Data
 * @param {number} collectionID
 * @param {boolean} replace
 * @returns {$CancellablePromise<$models.FileUploadResult | null>}
 */
export function UploadFile(filename, base64Data, collectionID, replace) {
    return $Call.ByID(31057319, filename, base64Data, collectionID, replace).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * WaitIngestIdle blocks until ingest finishes or timeout.
 * @param {number} timeoutMs
 * @returns {$CancellablePromise<void>}
 */
export function WaitIngestIdle(timeoutMs) {
    return $Call.ByID(1564228111, timeoutMs);
}

// Private type creation functions
const $$createType0 = $models.FileUploadResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = store$0.ChatMessage.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = store$0.ChatSession.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = store$0.Collection.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = store$0.Document.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.IngestJob.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = store$0.SourceChunkRef.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.IngestBatchResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.SearchResult.createFrom;
const $$createType17 = $Create.Array($$createType16);
