// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ArchiveChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(369086432, sessionID);
}

/**
 * CancelGeneration cancels an in-progress streaming generation for a session.
 */
export function CancelGeneration(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(4129843748, sessionID);
}

/**
 * CancelIngest requests cancellation of the active ingest worker.
 */
export function CancelIngest(): $CancellablePromise<void> {
    return $Call.ByID(2481471630);
}

/**
 * CheckFileHash checks if a file hash already exists in a collection.
 */
export function CheckFileHash(hash: string, collectionID: number): $CancellablePromise<$models.FileUploadResult | null> {
    return $Call.ByID(1617768898, hash, collectionID);
}

/**
 * CleanupIncompleteOnStartup removes staging rows and resets interrupted embedding jobs.
 */
export function CleanupIncompleteOnStartup(): $CancellablePromise<void> {
    return $Call.ByID(1378031294);
}

export function CreateChat(title: string, collectionID: number): $CancellablePromise<number> {
    return $Call.ByID(1198129586, title, collectionID);
}

export function CreateCollection(name: string): $CancellablePromise<number> {
    return $Call.ByID(870896888, name);
}

export function DeleteChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(3616999957, sessionID);
}

export function DeleteCollection(collectionID: number): $CancellablePromise<void> {
    return $Call.ByID(492526307, collectionID);
}

export function DeleteDocument(docID: number): $CancellablePromise<void> {
    return $Call.ByID(2035697934, docID);
}

/**
 * DiscardAllIncomplete deletes all non-ready documents.
 */
export function DiscardAllIncomplete(): $CancellablePromise<number> {
    return $Call.ByID(924053369);
}

/**
 * DiscardIngestJob deletes one incomplete document.
 */
export function DiscardIngestJob(docID: number): $CancellablePromise<void> {
    return $Call.ByID(2725518913, docID);
}

/**
 * FindDuplicateDocuments performs duplicate classification for a document before staging.
 */
export function FindDuplicateDocuments(collectionID: number, filename: string, content: string): $CancellablePromise<store$0.DuplicateMatch[] | null> {
    return $Call.ByID(717348378, collectionID, filename, content);
}

/**
 * GetChatBranchOptions returns sibling user prompts for the branch switcher.
 */
export function GetChatBranchOptions(sessionID: number, messageID: number): $CancellablePromise<store$0.ChatMessage[] | null> {
    return $Call.ByID(2474494412, sessionID, messageID);
}

export function GetChatMessages(sessionID: number): $CancellablePromise<store$0.ChatMessage[] | null> {
    return $Call.ByID(227903766, sessionID);
}

export function GetChats(): $CancellablePromise<store$0.ChatSession[] | null> {
    return $Call.ByID(3792084875);
}

/**
 * GetChunkContext returns the target chunk plus its parent and neighbor context.
 */
export function GetChunkContext(chunkID: number, radius: number): $CancellablePromise<store$0.ChunkRecord[] | null> {
    return $Call.ByID(4158516184, chunkID, radius);
}

export function GetCollections(): $CancellablePromise<store$0.Collection[] | null> {
    return $Call.ByID(3945395097);
}

/**
 * GetDocumentChunks returns all stored chunks for a document ordered by ord.
 */
export function GetDocumentChunks(docID: number): $CancellablePromise<store$0.ChunkRecord[] | null> {
    return $Call.ByID(2213676011, docID);
}

/**
 * GetDocumentContent returns the full extracted text content of a document.
 */
export function GetDocumentContent(docID: number): $CancellablePromise<string> {
    return $Call.ByID(4234809594, docID);
}

export function GetDocumentsByCollection(collectionID: number): $CancellablePromise<store$0.Document[] | null> {
    return $Call.ByID(1237202507, collectionID);
}

/**
 * GetEventLogs returns the recent workspace audit trail.
 */
export function GetEventLogs(limit: number): $CancellablePromise<store$0.EventLogEntry[] | null> {
    return $Call.ByID(2031385183, limit);
}

/**
 * GetIncompleteJobs returns non-ready documents for resume/discard UI.
 */
export function GetIncompleteJobs(): $CancellablePromise<$models.IngestJob[] | null> {
    return $Call.ByID(153934368);
}

/**
 * GetIngestionLogs returns the job logs for a particular ingestion job.
 */
export function GetIngestionLogs(jobID: number, limit: number): $CancellablePromise<store$0.IngestionLog[] | null> {
    return $Call.ByID(3524078849, jobID, limit);
}

/**
 * GetIngestionQueue returns persisted queue jobs for a collection.
 */
export function GetIngestionQueue(collectionID: number): $CancellablePromise<store$0.IngestionJob[] | null> {
    return $Call.ByID(1157729253, collectionID);
}

/**
 * GetMessageSources returns source chunks for a given message.
 */
export function GetMessageSources(msgID: number): $CancellablePromise<store$0.SourceChunkRef[] | null> {
    return $Call.ByID(2286181287, msgID);
}

/**
 * GetSessionMemory returns persisted rolling conversation memory rows for a session.
 */
export function GetSessionMemory(sessionID: number): $CancellablePromise<store$0.ChatSessionMemory[] | null> {
    return $Call.ByID(2894426603, sessionID);
}

/**
 * GetSessionSources returns source chunks all messages in a session.
 */
export function GetSessionSources(sessionID: number): $CancellablePromise<store$0.SourceChunkRef[] | null> {
    return $Call.ByID(2419631210, sessionID);
}

/**
 * IngestFile stages pasted text then embeds via the durable two-phase pipeline.
 */
export function IngestFile(collectionID: number, filename: string, fileContent: string): $CancellablePromise<void> {
    return $Call.ByID(1283934766, collectionID, filename, fileContent);
}

/**
 * IsIngesting reports whether staging/embedding is currently running.
 */
export function IsIngesting(): $CancellablePromise<boolean> {
    return $Call.ByID(1844145288);
}

/**
 * NewBatchID returns a new random batch identifier.
 */
export function NewBatchID(): $CancellablePromise<string> {
    return $Call.ByID(335305559);
}

/**
 * PauseIngest requests a graceful pause of the active ingest worker.
 */
export function PauseIngest(): $CancellablePromise<void> {
    return $Call.ByID(699990566);
}

export function PinChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(3755018561, sessionID);
}

/**
 * ResumeIngest continues embedding for all resumable incomplete documents.
 */
export function ResumeIngest(): $CancellablePromise<$models.IngestBatchResult | null> {
    return $Call.ByID(1682414391);
}

/**
 * RetryFailedIngest marks a job as retrying so the UI can trigger a resume.
 */
export function RetryFailedIngest(jobID: number): $CancellablePromise<void> {
    return $Call.ByID(3038328535, jobID);
}

export function Search(query: string, collectionID: number, topK: number): $CancellablePromise<$models.SearchResult[] | null> {
    return $Call.ByID(2413095468, query, collectionID, topK);
}

/**
 * SearchMetadata performs a document-level search over filenames, titles,
 * summaries and collection names.
 */
export function SearchMetadata(query: string, collectionID: number, topK: number): $CancellablePromise<$models.SearchResult[] | null> {
    return $Call.ByID(3659423273, query, collectionID, topK);
}

/**
 * SearchWorkspace expands retrieval to include the current session's cited source
 * chunks so the UI can search a working context, not just documents.
 */
export function SearchWorkspace(query: string, collectionID: number, sessionID: number, topK: number): $CancellablePromise<$models.SearchResult[] | null> {
    return $Call.ByID(1666949257, query, collectionID, sessionID, topK);
}

/**
 * SelectChatBranch switches the visible conversation to the selected prompt's branch.
 */
export function SelectChatBranch(sessionID: number, messageID: number): $CancellablePromise<void> {
    return $Call.ByID(689188206, sessionID, messageID);
}

export function SendMessage(sessionID: number, collectionID: number, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(279711485, sessionID, collectionID, prompt);
}

/**
 * StartIngestBatch stages every file first, then embeds all staged jobs in the batch.
 */
export function StartIngestBatch(collectionID: number, files: $models.IngestFilePayload[] | null): $CancellablePromise<$models.IngestBatchResult | null> {
    return $Call.ByID(3830860924, collectionID, files);
}

export function UnarchiveChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(3611384037, sessionID);
}

export function UnpinChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(206193300, sessionID);
}

export function UpdateChatTitle(sessionID: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(239667623, sessionID, title);
}

/**
 * UpdateCollectionProfile stores the embedding/vector profile for a collection.
 */
export function UpdateCollectionProfile(collectionID: number, embeddingModel: string, embeddingDims: number, vectorBackend: string): $CancellablePromise<void> {
    return $Call.ByID(3626765774, collectionID, embeddingModel, embeddingDims, vectorBackend);
}

/**
 * UploadFile stages one file then embeds it via the durable two-phase pipeline.
 * Prefer StartIngestBatch for multi-file uploads (extract-all-then-embed).
 */
export function UploadFile(filename: string, base64Data: string, collectionID: number, replace: boolean): $CancellablePromise<$models.FileUploadResult | null> {
    return $Call.ByID(31057319, filename, base64Data, collectionID, replace);
}

/**
 * WaitIngestIdle blocks until ingest finishes or timeout.
 */
export function WaitIngestIdle(timeoutMs: number): $CancellablePromise<void> {
    return $Call.ByID(1564228111, timeoutMs);
}
