// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * IngestFile accepts file content, splits it into chunks, embeds them, and saves them to the DB.
 */
export function IngestFile(collectionID: number, filename: string, fileContent: string): $CancellablePromise<void> {
    return $Call.ByID(1283934766, collectionID, filename, fileContent);
}

/**
 * SendMessage handles streaming LLM chat completions, retrieving dynamic database contexts if RAG is set up.
 */
export function SendMessage(sessionID: number, collectionID: number, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(279711485, sessionID, collectionID, prompt);
}
