// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ArchiveChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(369086432, sessionID);
}

/**
 * â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
 * CancelGeneration cancels an in-progress streaming generation for a session.
 */
export function CancelGeneration(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(4129843748, sessionID);
}

/**
 * CheckFileHash checks if a file hash already exists in a collection.
 */
export function CheckFileHash(hash: string, collectionID: number): $CancellablePromise<$models.FileUploadResult | null> {
    return $Call.ByID(1617768898, hash, collectionID);
}

export function CreateChat(title: string, collectionID: number): $CancellablePromise<number> {
    return $Call.ByID(1198129586, title, collectionID);
}

export function CreateCollection(name: string): $CancellablePromise<number> {
    return $Call.ByID(870896888, name);
}

export function DeleteChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(3616999957, sessionID);
}

export function DeleteCollection(collectionID: number): $CancellablePromise<void> {
    return $Call.ByID(492526307, collectionID);
}

export function DeleteDocument(docID: number): $CancellablePromise<void> {
    return $Call.ByID(2035697934, docID);
}

export function GetChatMessages(sessionID: number): $CancellablePromise<store$0.ChatMessage[] | null> {
    return $Call.ByID(227903766, sessionID);
}

export function GetChats(): $CancellablePromise<store$0.ChatSession[] | null> {
    return $Call.ByID(3792084875);
}

export function GetCollections(): $CancellablePromise<store$0.Collection[] | null> {
    return $Call.ByID(3945395097);
}

/**
 * GetDocumentContent returns the full extracted text content of a document.
 */
export function GetDocumentContent(docID: number): $CancellablePromise<string> {
    return $Call.ByID(4234809594, docID);
}

export function GetDocumentsByCollection(collectionID: number): $CancellablePromise<store$0.Document[] | null> {
    return $Call.ByID(1237202507, collectionID);
}

/**
 * GetMessageSources returns source chunks for a given message.
 */
export function GetMessageSources(msgID: number): $CancellablePromise<store$0.SourceChunkRef[] | null> {
    return $Call.ByID(2286181287, msgID);
}

/**
 * GetSessionSources returns source chunks all messages in a session.
 */
export function GetSessionSources(sessionID: number): $CancellablePromise<store$0.SourceChunkRef[] | null> {
    return $Call.ByID(2419631210, sessionID);
}

export function IngestFile(collectionID: number, filename: string, fileContent: string): $CancellablePromise<void> {
    return $Call.ByID(1283934766, collectionID, filename, fileContent);
}

export function PinChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(3755018561, sessionID);
}

export function Search(query: string, collectionID: number): $CancellablePromise<$models.SearchResult[] | null> {
    return $Call.ByID(2413095468, query, collectionID);
}

export function SendMessage(sessionID: number, collectionID: number, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(279711485, sessionID, collectionID, prompt);
}

export function UnarchiveChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(3611384037, sessionID);
}

export function UnpinChat(sessionID: number): $CancellablePromise<void> {
    return $Call.ByID(206193300, sessionID);
}

export function UpdateChatTitle(sessionID: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(239667623, sessionID, title);
}

/**
 * UploadFile handles file upload: base64 data -> extract text -> hash -> check dupe -> ingest.
 * If replace is true and file exists, it replaces the old content.
 */
export function UploadFile(filename: string, base64Data: string, collectionID: number, replace: boolean): $CancellablePromise<$models.FileUploadResult | null> {
    return $Call.ByID(31057319, filename, base64Data, collectionID, replace);
}
