// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * IngestFile accepts file content, splits it into chunks, embeds them, and saves them to the DB.
 * @param {number} collectionID
 * @param {string} filename
 * @param {string} fileContent
 * @returns {$CancellablePromise<void>}
 */
export function IngestFile(collectionID, filename, fileContent) {
    return $Call.ByID(1283934766, collectionID, filename, fileContent);
}

/**
 * SendMessage handles streaming LLM chat completions, retrieving dynamic database contexts if RAG is set up.
 * @param {number} sessionID
 * @param {number} collectionID
 * @param {string} prompt
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(sessionID, collectionID, prompt) {
    return $Call.ByID(279711485, sessionID, collectionID, prompt);
}
