// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileUploadResult {
    /**
     * Creates a new FileUploadResult instance.
     * @param {Partial<FileUploadResult>} [$$source = {}] - The source object to create the FileUploadResult.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "success", "duplicate", "error", "replaced"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["docId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["collectionName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["wordCount"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["chunkCount"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["existingDocId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["existingCreated"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileUploadResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileUploadResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileUploadResult(/** @type {Partial<FileUploadResult>} */($$parsedSource));
    }
}

/**
 * IngestBatchResult summarizes stage + embed for a batch.
 */
export class IngestBatchResult {
    /**
     * Creates a new IngestBatchResult instance.
     * @param {Partial<IngestBatchResult>} [$$source = {}] - The source object to create the IngestBatchResult.
     */
    constructor($$source = {}) {
        if (!("batchId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["batchId"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {StageResult[]}
             */
            this["items"] = [];
        }
        if (!("staged" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["staged"] = 0;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IngestBatchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IngestBatchResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new IngestBatchResult(/** @type {Partial<IngestBatchResult>} */($$parsedSource));
    }
}

/**
 * IngestFilePayload is one file or paste item in a batch.
 */
export class IngestFilePayload {
    /**
     * Creates a new IngestFilePayload instance.
     * @param {Partial<IngestFilePayload>} [$$source = {}] - The source object to create the IngestFilePayload.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("base64Data" in $$source)) {
            /**
             * file bytes (base64); empty when using TextContent
             * @member
             * @type {string}
             */
            this["base64Data"] = "";
        }
        if (!("textContent" in $$source)) {
            /**
             * paste path
             * @member
             * @type {string}
             */
            this["textContent"] = "";
        }
        if (!("replace" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["replace"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IngestFilePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IngestFilePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IngestFilePayload(/** @type {Partial<IngestFilePayload>} */($$parsedSource));
    }
}

/**
 * IngestJob is a durable incomplete/ready job exposed to the UI.
 */
export class IngestJob {
    /**
     * Creates a new IngestJob instance.
     * @param {Partial<IngestJob>} [$$source = {}] - The source object to create the IngestJob.
     */
    constructor($$source = {}) {
        if (!("docId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["docId"] = 0;
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("chunkCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunkCount"] = 0;
        }
        if (!("expectedChunks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedChunks"] = 0;
        }
        if (!("batchId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["batchId"] = "";
        }
        if (!("errorMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["errorMessage"] = "";
        }
        if (!("progressPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progressPct"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IngestJob instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IngestJob}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IngestJob(/** @type {Partial<IngestJob>} */($$parsedSource));
    }
}

export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("searchType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["searchType"] = "";
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("collectionName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collectionName"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("chunkId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunkId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * StageResult is the outcome of staging a single file/text.
 */
export class StageResult {
    /**
     * Creates a new StageResult instance.
     * @param {Partial<StageResult>} [$$source = {}] - The source object to create the StageResult.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * staged | duplicate | error | replaced
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["docId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StageResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StageResult(/** @type {Partial<StageResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = StageResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
