// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileUploadResult {
    /**
     * Creates a new FileUploadResult instance.
     * @param {Partial<FileUploadResult>} [$$source = {}] - The source object to create the FileUploadResult.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "success", "duplicate", "error", "replaced"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["docId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["collectionName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["wordCount"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["chunkCount"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["existingDocId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["existingCreated"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileUploadResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileUploadResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileUploadResult(/** @type {Partial<FileUploadResult>} */($$parsedSource));
    }
}

export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("searchType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["searchType"] = "";
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionId"] = 0;
        }
        if (!("collectionName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collectionName"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("chunkId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunkId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}
