// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FileUploadResult {
    "filename": string;

    /**
     * "success", "duplicate", "error", "replaced"
     */
    "status": string;
    "message": string;
    "docId"?: number;
    "collectionName"?: string;
    "wordCount"?: number;
    "chunkCount"?: number;
    "existingDocId"?: number;
    "existingCreated"?: number;
}

export interface SearchResult {
    "content": string;
    "score": number;
    "searchType": string;
    "collectionId": number;
    "collectionName": string;
    "filename": string;
    "chunkId": number;
}
