// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SearchResult {
    "content": string;
    "score": number;
    "searchType": string;
    "collectionId": number;
    "collectionName": string;
    "filename": string;
    "chunkId": number;
}
