// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DiagnosticsSnapshot {
    "dbReady": boolean;
    "goVersion": string;
    "goos": string;
    "goarch": string;
    "numCpu": number;
    "totalRamGb": number;
    "recommendedContextSize": number;
    "memoryAllocMb": number;
    "memorySysMb": number;
    "activeGenerations": number;
    "ingestActive": boolean;
    "collections": number;
    "chats": number;
    "messages": number;
    "documents": number;
    "readyDocuments": number;
    "incompleteDocuments": number;
    "chunks": number;
    "messageSources": number;
    "dbPageSize": number;
    "dbPageCount": number;
    "dbApproxBytes": number;
    "collectedAtUnix": number;
}

export interface FileUploadResult {
    "filename": string;

    /**
     * "success", "duplicate", "error", "replaced"
     */
    "status": string;
    "message": string;
    "docId"?: number;
    "collectionName"?: string;
    "wordCount"?: number;
    "chunkCount"?: number;
    "existingDocId"?: number;
    "existingCreated"?: number;
}

/**
 * IngestBatchResult summarizes stage + embed for a batch.
 */
export interface IngestBatchResult {
    "batchId": string;
    "items": StageResult[] | null;
    "staged": number;
    "completed": number;
    "failed": number;
    "cancelled": boolean;
}

/**
 * IngestFilePayload is one file or paste item in a batch.
 */
export interface IngestFilePayload {
    "filename": string;

    /**
     * file bytes (base64); empty when using TextContent
     */
    "base64Data": string;

    /**
     * paste path
     */
    "textContent": string;
    "replace": boolean;
}

/**
 * IngestJob is a durable incomplete/ready job exposed to the UI.
 */
export interface IngestJob {
    "docId": number;
    "collectionId": number;
    "filename": string;
    "status": string;
    "chunkCount": number;
    "expectedChunks": number;
    "batchId": string;
    "errorMessage": string;
    "progressPct": number;
    "updatedAt": number;
    "createdAt": number;
}

export interface SearchResult {
    "content": string;
    "score": number;
    "searchType": string;
    "collectionId": number;
    "collectionName": string;
    "filename": string;
    "title"?: string;
    "sectionPath"?: string;
    "chunkSummary"?: string;
    "chunkId": number;
}

/**
 * StageResult is the outcome of staging a single file/text.
 */
export interface StageResult {
    "filename": string;

    /**
     * staged | duplicate | error | replaced
     */
    "status": string;
    "message": string;
    "docId"?: number;
}
